{
 "title": "Backplane Live 2!!!",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "COTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avionics Bay BigRedBee",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT RKT_APRS_LAT, RKT_APRS_LONG, RKT_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Payload BigRedBee",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT PAY_APRS_LAT, PAY_APRS_LONG, PAY_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Altitude",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
     "targets": [
      {
       "query": "SELECT RKT_APRS_ALT, PAY_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;"
      }
     ]
    }
   ]
  },
  { "title": "Sensor Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Velocity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VELOCITY_Z FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VELOCITY_Z FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertical Acceleration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "LSM_ACCEL_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "TEMP_BMP388",
       "TEMP_TMP117",
       "TEMP_MS5611"
      ]
     }
    }
   ]
  },
  {
   "title": "Angular Velocity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "GYRO_X",
       "GYRO_Y",
       "GYRO_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Magnetic Field",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "MAGN_X",
       "MAGN_Y",
       "MAGN_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "LSM_ACCEL_X",
       "LSM_ACCEL_Y",
       "LSM_ACCEL_Z",
       "ADX_ACCEL_X",
       "ADX_ACCEL_Y",
       "ADX_ACCEL_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "PRESS_BMP388",
       "PRESS_MS5611"
      ]
     }
    }
   ]
  },
  {
   "title": "Angular Velocity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "GYRO_X",
       "GYRO_Y",
       "GYRO_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "TEMP_MS5611",
       "TEMP_BMP388",
       "TEMP_TMP117"
      ]
     }
    }
   ]
  },
  {
   "title": "Magnetic Field",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "MAGN_X",
       "MAGN_Y",
       "MAGN_Z"
      ]
     }
    }
   ]
  },
  {
   "title": "Temperature (Freedom Units)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "panelId": 32 }
   ]
  },
  { "title": "Radio Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "GNSS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LORA_RSSI, LORA_SNR, NUM_LORA_PACKETS FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "LoRa",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LORA_SNR, LORA_RSSI, NUM_LORA_PACKETS FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Power Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "VOLT_BATT",
       "VOLT_3V3",
       "VOLT_5V0"
      ]
     }
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "CURR_BATT",
       "CURR_3V3",
       "CURR_5V0"
      ]
     }
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "channel": "stream/telemetry/backplane",
     "filter": {
      "fields": [
       "time",
       "PWER_BATT",
       "PWER_3V3",
       "PWER_5V0"
      ]
     }
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  }
 ]
}