{
 "title": "Receiver",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "COTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avionics Bay BigRedBee",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT RKT_APRS_LAT, RKT_APRS_LONG, RKT_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Payload BigRedBee",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT PAY_APRS_LAT, PAY_APRS_LONG, PAY_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Altitude",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
     "targets": [
      {
       "query": "SELECT RKT_APRS_ALT, PAY_APRS_ALT FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;"
      }
     ]
    }
   ]
  },
  { "title": "Sensor Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ACCEL_X, ACCEL_Y, ACCEL_Z FROM gsw..backplane  WHERE $timeFilter;;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT PRESSURE FROM gsw..backplane WHERE $timeFilter;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Angular Velocity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT GYRO_X, GYRO_Y, GYRO_Z FROM gsw..backplane WHERE $timeFilter;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT TEMPERATURE FROM gsw..backplane WHERE $timeFilter;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature (Freedom Units)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n  TEMPERATURE * 9 / 5 + 32 AS TEMPERATURE_F\nFROM gsw..backplane WHERE $timeFilter;\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Radio Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT LATITUDE, LONGITUDE FROM gsw..backplane WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "GNSS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LATITUDE, LONGITUDE, ALTITUDE FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LoRa",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SNR, RSSI FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Power Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VOLT_BATT, VOLT_3V3, VOLT_5V0 FROM gsw..backplane WHERE $timeFilter;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VOLT_BATT, VOLT_3V3, VOLT_5V0 FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CURR_BATT, CURR_3V3, CURR_5V0 FROM gsw..backplane WHERE $timeFilter;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CURR_BATT, CURR_3V3, CURR_5V0 FROM gsw..backplane WHERE $timeFilter ORDER BY time DESC LIMIT 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}