name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:

  - uses: actions/checkout@v3
  
  - name: Install gomarkdoc
    run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

  - name: Generate Wiki Documentation
    run: |
      rm -rf wiki/* 
      mkdir -p wiki

      for dir in $(go list -f '{{.Dir}}' ./... | grep -v "cmd"); do
        gomarkdoc --output "./wiki/$(basename $dir).md" $dir
      done
    publish-wiki:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
